on:
  repository_dispatch:
    types:
      - test_trigger_true
  workflow_dispatch:
  
name: Remove Permissions
run-name: Remove ${{ github.event.client_payload.acc_name }} ${{ github.event.client_payload.acc_role }}

jobs:
  dispatch_success:
    if: ${{ github.event.client_payload.test_success}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Success"
      - run: echo ${{ github.event.client_payload.message }}

  manage_user:
    runs-on: ubuntu-latest
    name: Delete ${{ github.event.client_payload.acc_name }} Perms
    env:
      AWS_ACC: ${{ github.event.client_payload.aws_acc }}
      SEC_TEST: ${{ github.event.client_payload.sec_test}}
      ACC_NAME: ${{ github.event.client_payload.acc_name }}
      AWS_ROLE: ${{ github.event.client_payload.acc_role }}
    steps:
      - run: echo "AWS Acc to use - $AWS_ACC"
      - run: echo "Account to change - $ACC_NAME"
      - run: echo "Role to manage - $AWS_ROLE"
  