on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  dispatch_success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Success"
      - run: echo ${{ github.event.client_payload.message }}