on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: "Username"
      groups:
        required: true
        type: string
        description: "Comma separated list of groups (e.g. group1,group2)"
      project:
        required: true
        description: "Project user is in"
        type: choice
        options:
          - henosis
          - hr
          - skyforge

name: Give User Permissions
    
jobs:
  setup:
    name: Setup Matrix
    runs-on: ubuntu-latest
    outputs:
      groups_list: ${{ steps.vars.outputs.groups_list }}
    steps:
      - name: Create an array of groups
        id: vars
        run: echo "::set-output name=groups_list::$(jq 'split(",")' -Rc <(echo '${{ inputs.groups }}'))"

  call-aws:
    name: Give ${{ inputs.name }} ${{ matrix.groups }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groups: ${{ fromJson(needs.setup.outputs.groups_list) }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials # Auth to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          group-to-assume: arn:aws:iam::${{ secrets.AWS_ACC_ID }}:role/${{ secrets.AWS_ROLE }}
          aws-region: eu-west-2
      - name: Replace Name
        run: |
          old=$( cat input.json )
          replace=${{ inputs.name }}
          new=${old/item1/$replace}
          echo $old $new
          echo $new > input.json
      - name: Replace group
        run: |
          old=$( cat input.json )
          replace=${{ matrix.groups }}
          new=${old/item2/$replace}
          echo $old $new
          echo $new > input.json
      - name: Execute AWS StepFunction
        run: aws stepfunctions start-execution --state-machine-arn arn:aws:states:eu-west-2:335840475404:stateMachine:jit-test-state-eoin --name actions-test-exec --input file://input.json
